//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface FlavorDto {
    id?: string;
    name?: string | undefined;
}

export interface PackDto {
    id?: string;
    size?: number;
    unit?: string | undefined;
    prices?: PriceDto[] | undefined;
}

export interface PriceDto {
    id?: string;
    productPackId?: string;
    price?: number;
    validFrom?: Date;
    validTo?: Date | undefined;
}

export interface ProductReadDto {
    id?: string;
    createdOn?: Date;
    updatedOn?: Date | undefined;
    name?: string | undefined;
    description?: string | undefined;
    sku?: string | undefined;
    quantityInStock?: number;
    isActive?: boolean;
    flavors?: FlavorDto[] | undefined;
    specifications?: SpecificationDto[] | undefined;
    packs?: PackDto[] | undefined;
    ratings?: RatingDto[] | undefined;
}

export interface RatingDto {
    id?: string;
    userId?: string;
    rating?: number;
    comment?: string | undefined;
}

export interface SpecificationDto {
    id?: string;
    name?: string | undefined;
    value?: string | undefined;
}

export interface ProductDisplay {
  id: string;
  name: string;
  description?: string;
  flavorName: string;
  flavorColor?: string;
  packs: { id: string; label: string }[];
}